Error occurred during infeed/outfeed. 
This may be due to a compile error in the main session. 
Waiting for a short time for the main session to come back. 
Shape [?,1] is not fully defined [[Node: input_pipeline_task0/InfeedQueue/enqueue/0 = InfeedEnqueueTuple[device_ordinal=0, dtypes=[DT_INT64, DT_FLOAT, DT_INT64, DT_INT64], shapes=[[?,1], [?,?], [?,2], [?,1]], _device="/job:worker/replica:0/task:0/device:CPU:0"](input_pipeline_task0/IteratorGetNext, input_pipeline_task0/IteratorGetNext:1, input_pipeline_task0/IteratorGetNext:2, input_pipeline_task0/IteratorGetNext:3)]] Caused by op u'input_pipeline_task0/InfeedQueue/enqueue/0', defined at: File "tmt.py", line 470, in <module> tf.app.run(main=main, argv=[sys.argv[0]] + unparsed) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run _sys.exit(main(argv)) File "tmt.py", line 336, in main estimator.train(input_fn=train_input_fn, max_steps=FLAGS.train_steps) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 366, in train loss = self._train_model(input_fn, hooks, saving_listeners) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1119, in _train_model return self._train_model_default(input_fn, hooks, saving_listeners) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1132, in _train_model_default features, labels, model_fn_lib.ModeKeys.TRAIN, self.config) File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 1992, in _call_model_fn features, labels, mode, config) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1107, in _call_model_fn model_fn_results = self._model_fn(features=features, **kwargs) File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2212, in _model_fn input_holders.generate_infeed_enqueue_ops_and_dequeue_fn()) File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 1001, in generate_infeed_enqueue_ops_and_dequeue_fn self._invoke_input_fn_and_record_structure()) File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 1089, in _invoke_input_fn_and_record_structure enqueue_ops.append(enqueue_ops_fn()) File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 748, in enqueue_ops_fn tpu_ordinal_function=tpu_ordinal_function)) File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_feed.py", line 631, in split_inputs_and_generate_enqueue_ops for (shard, index) in zip(sharded_inputs, xrange(self.number_of_shards)) File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_feed.py", line 462, in _generate_enqueue_op device_ordinal=tpu_ordinal) File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/ops/gen_tpu_ops.py", line 440, in infeed_enqueue_tuple device_ordinal=device_ordinal, name=name) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper op_def=op_def) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3414, in create_op op_def=op_def) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1740, in __init__ self._traceback = self._graph._extract_stack() # pylint: disable=protected-access InvalidArgumentError (see above for traceback): Shape [?,1] is not fully defined [[Node: input_pipeline_task0/InfeedQueue/enqueue/0 = InfeedEnqueueTuple[device_ordinal=0, dtypes=[DT_INT64, DT_FLOAT, DT_INT64, DT_INT64], shapes=[[?,1], [?,?], [?,2], [?,1]], _device="/job:worker/replica:0/task:0/device:CPU:0"](input_pipeline_task0/IteratorGetNext, 
